#### setup database:
###
POST http://localhost:8080/addAuthorsAndPosts

#### posts:
###

GET http://localhost:8080/allPostsByAuthor/vasya%20pupkin

###
GET http://localhost:8080/allPostsByAuthor2/ivan%20fedorovich%20pahomov



###
GET http://localhost:8080/allPostsByAuthorId/1


###
GET http://localhost:8080/allPostsByAuthorNick/afrodita


###
GET http://localhost:8080/allDrafts



###
GET http://localhost:8080/postsByTitle/america


###
GET http://localhost:8080/allPosts


#### comments:
###
GET http://localhost:8080/allComments


###
GET http://localhost:8080/lastAuthorId



###
GET http://localhost:8080/commentsByPostAndAuthor/1-2



###
GET http://localhost:8080/commentsByPost/1



###
GET http://localhost:8080/commentsByContents/a

##### authors:
###
GET http://localhost:8080/allAuthors


###
GET http://localhost:8080/authorByName/ma


###
GET http://localhost:8080/authorsByNick/monster


###
GET http://localhost:8080/authorById/3


###
GET http://localhost:8080/authorByName/ivan


