micronaut:
  application:
    name: micronaut-r2dbc-test
flyway:
  datasources:
    default:
      enabled: true
datasources:
  default:
    url: jdbc:h2:mem:default;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: none
    dialect: H2
r2dbc:
  datasources:
    default:
      dialect: H2
      url: r2dbc:h2:mem:///default
      username: sa
      password: ''

